hoarding/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hoarding.views.home', name='home'),
    # url(r'^hoarding/', include('hoarding.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/$', 'hoardingusers.views.HoardingUserRegistration'),
    
    url(r'^login/$', 'hoardingusers.views.LoginRequest'),    
    url(r'^logout/$', 'hoardingusers.views.LogoutRequest'),
    
    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset'),
    url(r'^reset/done$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^profile/$', 'hoardingusers.views.Profile'),
    
    url(r'^hoarding/$', 'hoarding.views.AddHoarding'),
)

hoarding/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class MediaType(models.Model):
    name        = models.CharField(max_length=250)
    flag        = models.SmallIntegerField(default=0)
    created     = models.DateTimeField(default=datetime.datetime.now())
    updated     = models.DateTimeField(default=None)
    comment     = models.TextField(null=True);

    def __unicode__(self):
        return self.name
    
    
class HoardingType(models.Model):
    name        = models.CharField(max_length=250)
    flag        = models.SmallIntegerField(default=0)
    created     = models.DateTimeField(default=datetime.datetime.now())
    updated     = models.DateTimeField(default=None)
    comment     = models.TextField(null=True);

    def __unicode__(self):
        return self.name


#This sotres the user entered hoarding information
class Hoarding(models.Model):
    town                = models.CharField(max_length=250)
    user                = models.ForeignKey(User)
    media_type          = models.ForeignKey(MediaType)
    width               = models.IntegerField(default=0)
    height              = models.IntegerField(default=0)   
    hoarding_type       = models.ForeignKey(HoardingType)  
    area_particulars    = models.TextField(null=True);
    units               = models.SmallIntegerField(default=0)  
    latitude            = models.DecimalField(null=True, max_digits=30, decimal_places=25);
    longitude           = models.DecimalField(null=True, max_digits=30, decimal_places=25);
    diaplay_cost        = models.IntegerField(default=0)
    production_cost     = models.IntegerField(default=0)
    mounting_cost       = models.IntegerField(default=0)
    enabled             = models.BooleanField(default=True)
    deleted             = models.BooleanField(default=False)
    created             = models.DateTimeField(default=datetime.datetime.now())
    updated             = models.DateTimeField(default=datetime.datetime.now())
    comment             = models.TextField(null=True);
    
    def __unicode__(self):
        return self.town

    

hoarding/forms.py
from django import forms
from django.forms import ModelForm
from hoarding.models import Hoarding

class HoardingForm(ModelForm):
    
    class Meta:
        model   = Hoarding
        exclude = ('user', 'enabled', 'deleted', 'created', 'updated', 'comment')
    
   
    
    

hoarding/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse
import json
from django.shortcuts import render_to_response
from django.template import RequestContext
from hoarding.forms import HoardingForm
from hoardingusers.forms import LoginForm
from hoarding.models import Hoarding
from django.contrib.auth.decorators import login_required


@login_required
def AddHoarding(request):
    if request.user.is_authenticated() :
        form = HoardingForm()
        if request.method == "POST" :
            form = HoardingForm(request.POST)
            if form.is_valid() :
                hoarding = Hoarding(user                = request.user, 
                                    town                = form.cleaned_data['town'], 
                                    media_type          = form.cleaned_data['media_type'],
                                    width               = form.cleaned_data['width'],
                                    height              = form.cleaned_data['height'],
                                    hoarding_type       = form.cleaned_data['hoarding_type'],
                                    area_particulars    = form.cleaned_data['area_particulars'],
                                    units               = form.cleaned_data['units'],
                                    latitude            = form.cleaned_data['latitude'],
                                    longitude           = form.cleaned_data['longitude'],
                                    diaplay_cost        = form.cleaned_data['diaplay_cost'],
                                    production_cost     = form.cleaned_data['production_cost'],
                                    mounting_cost       = form.cleaned_data['mounting_cost']                                    
                                     )
                hoarding.save()
                #return HttpResponseRedirect('/')
                response_data = {'rslt' : True, 'msg' : 'sucess'}
                return HttpResponse(json.dumps(response_data), mimetype="application/json")
            else :
                context = {'form': form}
                return render_to_response("add_hoarding.html", context, context_instance=RequestContext(request))
        else :
                context = {'form': form}
                return render_to_response("add_hoarding.html", context, context_instance=RequestContext(request))    
    else :
        '''user is not submitting the form, show the login form '''
        form = LoginForm
        context = {'form' : form}
        return render_to_response('login.html', context, context_instance=RequestContext(request))
    
    
    
    




    
    
    
    

hoarding/templates/add_hoarding.html
<script type="text/javascript" src="http://j.maxmind.com/app/geoip.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.4.0/jquery.js"></script>


<script>
	/*
	
	var map;
	var myLatlng;
	function initialize() {
		myLatlng =  new google.maps.LatLng(lat_, long_);
		var mapOptions = {
			zoom: 15,
			center: myLatlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);	 
		var marker = new google.maps.Marker(
							{ position: myLatlng, title:"Hello World!"}
						);

		marker.setMap(map);
	}

	google.maps.event.addDomListener(window, 'load', initialize);	
	*/
	
	
	var map;
	var markersArray = [];
	var lat_ = geoip_latitude();
	var long_ = geoip_longitude();
	
	function initialize() {
	  var haightAshbury = new google.maps.LatLng(lat_, long_);
	  var mapOptions = {
		zoom: 12,
		center: haightAshbury,
		mapTypeId: google.maps.MapTypeId.TERRAIN
	  };
	  map =  new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

	  google.maps.event.addListener(map, 'click', function(event) {
		addMarker(event.latLng);
	  });
	}

	function addMarker(location) {
	  deleteOverlays();
	  marker = new google.maps.Marker({
		position: location,
		map: map
	  });
	  markersArray.push(marker);
	  getAddress(location);
	}

	// Removes the overlays from the map, but keeps them in the array
	function clearOverlays() {
	  if (markersArray) {
		for (i in markersArray) {
		  markersArray[i].setMap(null);
		}
	  }
	}

	// Shows any overlays currently in the array
	function showOverlays() {
	  if (markersArray) {
		for (i in markersArray) {
		  markersArray[i].setMap(map);
		}
	  }
	}

	// Deletes all markers in the array by removing references to them
	function deleteOverlays() {
	  if (markersArray) {
		for (i in markersArray) {
		  markersArray[i].setMap(null);
		}
		markersArray.length = 0;
	  }
	}

	
	google.maps.event.addDomListener(window, 'load', initialize);

	
	function getAddress(latLng) {
		var geocoder = new google.maps.Geocoder();
		geocoder.geocode( {'latLng': latLng},
			  function(results, status) {
				if(status == google.maps.GeocoderStatus.OK) {
				  if(results[0]) {
					$('#id_area_particulars').val(results[0].formatted_address);
					$('#id_latitude').val(latLng.lat());
	  				$('#id_longitude').val(latLng.lng());
					/*
					for (j in results) {
						console.log(results[j]);
					}
					*/
				  }
				  else {
					//document.getElementById("address").value = "No results";
				  }
				}
				else {
				  //document.getElementById("address").value = status;
				}
			  });
	}

</script>

<style>
  html, body, #map-canvas {
    margin: 0;
    padding: 0;
    height: 100%;
  }
</style>
 
 
<div id="map-canvas"></div>

 
<form action="" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="submit" name="submit"/>
<input type="reset" value="reset" name="reset"/>
</form>

hoarding/templates/header.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>{% block title %}UglyWorkz{% endblock %}</title>
		<meta name="description" content="" />
		<meta name="author" content="Administrator" />

		<meta name="viewport" content="width=device-width; initial-scale=1.0" />

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
		<link href="../static/css/base.css" rel="stylesheet" type="text/css"/>
		<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css"/>
		<script type="text/javascript" src="../static/js/jquery.js"></script>
		<script type="text/javascript" src="../static/js/bootstrap.js"></script>
	<body>
		<header><div class="container">UglyWorkz</div></header>
			
			<div class="container" >
				 {% block login %} {% endblock %}
			</div>

			<footer>
				 <div class="container">&copy; 2013 Ugly workz india pvt Ltd.</div>
			</footer>	
	</body>
</html>

hoarding/templates/login.html
{% extends "header.html" %}
{% block login %}
<script type="text/javascript">
	$('#myTab a').click(function(e) {
		e.preventDefault();
		$(this).tab('show');
	}); 
</script>
</head>
<div class="tabbable">
	<ul class="nav nav-tabs" id="myTab">
		<li class="active">
			<a href="#Login" data-toggle="tab"><i class="icon-user"></i> Login</a>
		</li>
		<li>
			<a href="#Register" data-toggle="tab"><i class="icon-pencil"></i> Register</a>
		</li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active span7 offset2" id="Login">
			<form action="" method="post" class="form well">
				<fieldset>
					<legend>
						Existing Users Login
					</legend>
					{% csrf_token %}
					{% if form.username.errors %}
					<div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">
							&times;
						</button>
						{{ form.username.errors|striptags }}
					</div>
					{% endif %}

					<label for="username">Username</label>
					<div class="input-prepend">
						<span class="add-on"><i class="icon-user"></i></span>
						<input id="id_username" name="username" type="text" class="span6" />
					</div>
					{% if form.password.errors %}
					<div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">
							&times;
						</button>
						{{ form.password.errors|striptags }}
					</div>
					{% endif %}

					<label>Password :</label>
					<div class="input-prepend">
						<span class="add-on"><i class="icon-lock"></i></span>
						<input id="id_password" name="password" type="password" class="span6" />
					</div>
					<input type="submit" value="submit" name="submit" class="btn btn-inverse" />
					&nbsp;
					<input type="reset" value="reset" name="reset" class="btn btn-inverse" />
					<div class="clear"></div>
					<div align="right">
						Forgot password? <a href="#">Click here to reset</a>
					</div>
					<div class="clear"></div>
				</fieldset>
			</form>
		</div>
		<div class="tab-pane fade in span7 offset2" id="Register">
			<form action="" method="post">
				{% csrf_token %}
				{% if form.username.errors %}
				<div>
					{{ form.username.errors }}
				</div>
				{% endif %}
				<div>
					<label>User Name :</label>
					{{ form.username }}
				</div>

				{% if form.email.errors %}
				<div>
					{{ form.email.errors }}
				</div>
				{% endif %}
				<div>
					<label>Email :</label>
					{{ form.email }}
				</div>

				{% if form.user_type.errors %}
				<div>
					{{ form.user_type.errors }}
				</div>
				{% endif %}
				<div>
					<label>Type :</label>
					{{ form.user_type }}
				</div>

				{% if form.password.errors %}
				<div>
					{{ form.password.errors }}
				</div>
				{% endif %}
				<div>
					<label>Password :</label>
					{{ form.password }}
				</div>

				{% if form.password1.errors %}
				<div>
					{{ form.password1.errors }}
				</div>
				{% endif %}
				<div>
					<label>Verify Password :</label>
					{{ form.password1 }}
				</div>
				<input type="submit" value="submit" name="submit"/>
				<input type="reset" value="reset" name="reset"/>
			</form>
		</div>
	</div>

</div>
</div>
{% endblock %}

hoarding/templates/profile.html
<p>
	Name = {{ profile.user_type.slug }}
	Name = {{ profile.user.username }}
	
	
	{% for hoarding in hoardings %}
		<br/>
		{{hoarding.town}}, {{hoarding.area_particulars}}
	{% endfor %}
	
</p>

hoarding/templates/register.html
<form action="" method="post">
	{% csrf_token %}
	{% if form.username.errors %}
	<div>
		{{ form.username.errors }}
	</div>
	{% endif %}
	<div>
		<label>User Name :</label>
		{{ form.username }}
	</div>

	{% if form.email.errors %}
	<div>
		{{ form.email.errors }}
	</div>
	{% endif %}
	<div>
		<label>Email :</label>
		{{ form.email }}
	</div>

	{% if form.user_type.errors %}
	<div>
		{{ form.user_type.errors }}
	</div>
	{% endif %}
	<div>
		<label>Type :</label>
		{{ form.user_type }}
	</div>

	{% if form.password.errors %}
	<div>
		{{ form.password.errors }}
	</div>
	{% endif %}
	<div>
		<label>Password :</label>
		{{ form.password }}
	</div>

	{% if form.password1.errors %}
	<div>
		{{ form.password1.errors }}
	</div>
	{% endif %}
	<div>
		<label>Verify Password :</label>
		{{ form.password1 }}
	</div>

	<input type="submit" value="submit" name="submit"/>
	<input type="reset" value="reset" name="reset"/>
</form>